name: Trigger AEP Spec Update

on:
  push:
    branches:
      - m2

jobs:
  dispatch-update-specs:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger AEP Spec Update in akash-network/website repo
        run: |
          repo_owner="akash-network"
          repo_name="website"
          event_type="aep-repo-trigger"

          STATUS=$(curl -s -o /dev/null -w "%{http_code}" -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_WEBSITE_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
            -d "{\"event_type\": \"$event_type\"}")

          [[ "$STATUS" -ge 200 && "$STATUS" -lt 300 ]] || { echo "Error: HTTP $STATUS"; exit 1; }
